#!groovy

// Generated by IBM TransformationAdvisor
// Fri Apr 12 11:10:03 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'customerorderservicesapp'
    mvnCommands = '--version'
    test='false'
}